apiVersion: v1
kind: Service
metadata:
  name: interceptor-proxy
  namespace: test-project
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
    - port: 8080
      targetPort: 8080
